import Head from 'next/head';
import Footer from './Footer';
import Header from './Header';
import styles from "../../styles/Layout.module.scss"

export default function Layout({ children, info }) {
    return (
        <>
            <Head >
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header info={info} />
            <main className={styles.mainContainer} >
                {children}
            </main>
            <Footer />
        </>
    )
}