import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { DataStore } from '@aws-amplify/datastore';
import { Student } from '../src/models';

export default function Home() {
  const [students, setStudents] = useState([])

  useEffect(() => {
    fetchStudents()
    async function fetchStudents() {
      const studentData = await DataStore.query(Student);
      setStudents(studentData)
      console.log(studentData);
    }

  }, [])

  console.log(students)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hi</h1>
        {students.map(student => {
          return (
            <div key={student.id}>
              <Link href={`/students/${student.id}`}>
                <a>{student.content}</a>
              </Link>
            </div>
          )
        })}
      </main>


    </div>
  )
}
